---
apiVersion: v1
kind: Secret
metadata:
  name: azure-service-key
  namespace: opencost
type: Opaque
stringData:
  service-key.json: |-
    {
      "subscriptionId": ${subscription_id}
      "serviceKey": {
          "appId": ${app_id}
          "displayName": "AZ-CSGNA-SPN-SRE-Prod-0001"
          "password": ${secret_key}
          "tenant": ${tenant_id}
      }
    }
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: opencost-env
# type: Opaque
# data:
# {{- range $key, $value := .Values.secrets }}
#   {{ $key | quote }}: {{ $value | b64enc | quote }}
# {{- end }}


# apiVersion: v1
# kind: Secret
# metadata:
#   name: opencost-env
# type: Opaque
# stringData:
# {{- range $key, $value := .Values.secrets }}
#   {{ $key }}: {{ $value }}
# {{- end }}
