ui:
  enabled: true
injector:
  enabled: false
server:
  enabled: true
  standalone:
    enabled: true
    nodeSelector:
      app: api
  ingress:
    enabled: True
    ingressClassName: nginx
    pathType: Prefix
    activeService: true
    hosts:
      - host: vault.qa1.csgna.cloud.tbintra.net
    tls:
     - secretName: ingress-local-tls
       hosts:
         - vault.qa1.csgna.cloud.tbintra.net